---
- name: LOCAL | PRE-SETUP DM MULTIPATH LVM
  include_tasks: presetup-local-lvm.yml

- name: LOCAL | PRE-SETUP DM MULTIPATH BOOT DISK FSTAB
  include_tasks: presetup-local-bootfstab.yml

- name: LOCAL | PRE-SETUP DM MULTIPATH BOOTEFI DISK FSTAB (UEFI)
  include_tasks: presetup-local-bootefifstab.yml
  when:
    - reg_stat_uefi_enabled.stat.isdir is defined
    - reg_stat_uefi_enabled.stat.isdir
